name: oars
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda-pack=0.7.0=pyh6c4a22f_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1=cuda11.3_0
  - cupti=11.3.1=0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.20.1=h4ff587b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.0=hecacb30_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - magma=2.7.0=h8db6258_0
  - mkl=2021.4.0=h06a4308_640
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy-base=1.23.5=py310h8e6c178_0
  - openssl=1.1.1t=h7f8727e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - python=3.10.9=h7a1cb2a_0
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.4.0=py310h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - adversarial-robustness-toolbox==1.13.0
    - asttokens==2.2.1
    - astunparse==1.6.3
    - backcall==0.2.0
    - brotlipy==0.7.0
    - cachetools==5.3.0
    - cffi==1.15.1
    - colorama==0.4.6
    - contourpy==1.0.7
    - cryptography==38.0.4
    - cycler==0.11.0
    - cython==0.29.33
    - decorator==5.1.1
    - dill==0.3.6
    - eagerpy==0.30.0
    - executing==1.2.0
    - flatbuffers==2.0.7
    - fonttools==4.38.0
    - foolbox==3.3.3
    - future==0.18.2
    - gast==0.4.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - google-auth==2.16.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.51.1
    - h5py==3.8.0
    - icecream==2.1.3
    - idna==3.4
    - imagehash==4.3.1
    - imageio==2.27.0
    - ipdb==0.13.13
    - ipython==8.9.0
    - jax==0.4.8
    - jedi==0.18.2
    - joblib==1.2.0
    - kaggle==1.5.13
    - keras==2.12.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - libclang==16.0.0
    - llvmlite==0.39.1
    - lpips==0.1.4
    - markdown==3.4.1
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - ml-dtypes==0.1.0
    - networkx==3.1
    - numba==0.56.4
    - numpy==1.23.5
    - oauthlib==3.2.2
    - onnx==1.13.1
    - onnx2pytorch==0.4.1
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - packaging==23.0
    - pandas==1.5.3
    - parse==1.19.0
    - parso==0.8.3
    - pdqhash==0.2.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pip==22.3.1
    - prompt-toolkit==3.0.36
    - protobuf==3.20.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - python-slugify==8.0.1
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.20.0
    - scikit-learn==1.1.3
    - scipy==1.10.0
    - setuptools==65.6.3
    - sha256==0.3
    - smmap==5.0.0
    - stack-data==0.6.2
    - tensorboard==2.12.2
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.2.0
    - text-unidecode==1.3
    - tf2onnx==1.14.0
    - threadpoolctl==3.1.0
    - tifffile==2023.3.21
    - tomli==2.0.1
    - torch==1.12.1
    - torch-dct==0.1.6
    - torchvision==0.13.1
    - tqdm==4.64.1
    - traitlets==5.9.0
    - typing-extensions==4.4.0
    - urllib3==1.26.14
    - wcwidth==0.2.6
    - werkzeug==2.2.2
    - wrapt==1.14.1
